mod_page_download_ui <- function(id) {
    ns <- NS(id)

    # Define colors from app theme
    col_navy <- "#1D3557" # Headings
    col_slate <- "#6574B9" # Primary
    col_grey <- "#f8f9fa" # Backgrounds

    tagList(
        # --- Main Dashboard Container ---
        tags$div(
            class = "container-fluid",
            style = "padding-top: 30px; max-width: 1200px;",

            # --- Header Section (Matches other dashboard pages) ---
            tags$div(
                style = "margin-bottom: 30px;",
                h2(tags$span(icon("file-download"), style = paste0("color:", col_slate, "; margin-right: 10px;")),
                    "Export Analysis",
                    style = paste0("color:", col_navy, "; font-weight: 700;")
                ),
                p("Download the comprehensive findings and data summary generated by this dashboard.",
                    style = "color: #6c757d; font-size: 1.1rem;"
                )
            ),

            # --- Content Row ---
            fluidRow(
                # --- Left Column: Context ---
                column(
                    width = 8,

                    # Card: Executive Summary
                    div(
                        class = "card shadow-sm mb-4",
                        style = "border: none; border-left: 5px solid #6574B9;", # Slate accent
                        div(
                            class = "card-body",
                            h4("Executive Summary", class = "card-title", style = paste0("color:", col_navy, "; font-weight: 600;")),
                            p("The report provides a triangulated analysis of climate responsibility, synthesizing data from:", class = "card-text", style = "margin-top: 15px; color: #495057;"),
                            tags$ul(
                                style = "color: #495057; margin-bottom: 20px;",
                                tags$li(tags$strong("Geography:"), " Contrasting absolute vs. per-capita metrics across nations."),
                                tags$li(tags$strong("Sectors:"), " Breaking down emissions by economic activity (Energy, Ag, etc.)."),
                                tags$li(tags$strong("Corporations:"), " Identifying the top 174 'Carbon Majors' driving supply.")
                            ),
                            p("Use this document for offline review, academic citation, or policy presentation.", class = "text-muted")
                        )
                    ),

                    # Card: Metadata
                    div(
                        class = "card shadow-sm",
                        style = "border: none;",
                        div(
                            class = "card-body",
                            h5("Report Metadata", class = "card-title", style = "color: #1D3557;"),
                            tags$table(
                                class = "table table-borderless table-sm",
                                style = "color: #6c757d;",
                                tags$tr(
                                    tags$td(tags$strong("Generated Date:")),
                                    tags$td(format(Sys.Date(), "%B %d, %Y"))
                                ),
                                tags$tr(
                                    tags$td(tags$strong("Data Sources:")),
                                    tags$td("EDGAR v8.0, Carbon Majors Database, Our World In Data")
                                ),
                                tags$tr(
                                    tags$td(tags$strong("Format:")),
                                    tags$td("PDF Document")
                                )
                            )
                        )
                    )
                ),

                # --- Right Column: Action ---
                column(
                    width = 4,

                    # Card: Download Action
                    div(
                        class = "card shadow-sm text-center",
                        style = "border: none; background-color: #f8f9fa;",
                        div(
                            class = "card-body",
                            style = "padding: 40px 20px;",
                            icon("file-pdf", "fa-4x", style = "color: #6574B9; margin-bottom: 20px;"), # Slate icon
                            h4("Full PDF Report", style = paste0("color:", col_navy, ";")),
                            p("Includes all visualizations, methodology, and conclusion text.", style = "color: #6c757d; font-size: 0.9rem; margin-bottom: 25px;"),

                            # Download Button styled as a large customized button
                            downloadButton(
                                ns("download_report"),
                                "Download Now (PDF)",
                                class = "btn btn-primary btn-lg w-100",
                                style = "background-color: #2c3e50; border: none; font-weight: 600;" # Navy button
                            )
                        )
                    )
                )
            )
        )
    )
}

mod_page_download_server <- function(id) {
    moduleServer(id, function(input, output, session) {
        output$download_report <- downloadHandler(
            filename = function() {
                paste("Datavisualization_Report_", format(Sys.Date(), "%Y-%m-%d"), ".pdf", sep = "")
            },
            content = function(file) {
                # Copy the pre-existing PDF to the download stream
                file.copy("Report.pdf", file)
            }
        )
    })
}
